name: Unit Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # checkout@v6.0.2

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # setup-go@v6.0.4  
        with:
          go-version-file: src/go.mod

      - name: Run tests
        run: go test -v -count=1 -race ./...
